package KieRule;
import com.example.drools.Order;

rule "HSBC"
    when
        orderObject: Order(cardType == "HSBC" && price > 10000);
    then
        orderObject.setDiscount(10);
end;

rule "ICICI"
    when
        orderObject: Order(cardType == "ICICI" && price > 15000);
    then
        orderObject.setDiscount(8);
end;

rule "SBI"
    when
        orderObject: Order(cardType == "SBI" && price > 15000);
    then
    orderObject.setDiscount(15);
end;

rule "SC"
    when
        orderObject: Order(cardType == "SC" && price > 20000);
    then
    orderObject.setDiscount(20);
end;